id: P006764
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:21:42.308638
source_metadata:
  id: bdr:W3CN547
  title: གཞོམ་མེད་ཀྱི་ནཱ་ད།
  author: ''
  volumes:
    0241a1b9008049cdbaf1546f4b3b1aa0:
      image_group_id: I3CN3963
      title: ''
      volume_number: 1
      total_pages: 132
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
